### ISSUE TITLE
depends on python-gnome2 which is deprecated

### ISSUE THREAD

**Issue by ginggs** [andrewbird/wader#12]
Forwarded from [Debian bug #845958](https://bugs.debian.org/845958):

> wader depends on python-gnome2 or python-gconf, or has a
> build-dependency on one those packages. Those are built from
> gnome-python which is long deprecated and going to be removed from
> the archive. wader should be ported away from it.
> 
> The way forward is to port your app to use GObject Introspection
> bindings.
> 
> For more information on GObject Introspection see [1] and [2].
> 
> Please try to do this before the Stretch release as we're going to
> try to remove gnome-python this cycle.
> 
> If you have any question don't hesitate to ask.
> 
> [1] https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
> [2] https://wiki.gnome.org/action/show/Projects/PyGObject 
>

**Comment by andrewbird** [comment]
Hi Graham,
   I'm not sure Wader is used or relevant on a modern system and it's not something I spend any time on maintaining any more. It's probably better to remove it from Debian than to fix these issues. 

Thanks,

Andrew

**Comment by ginggs** [comment]
Agreed, thanks.

**Comment by andrewbird** [comment]
Agreed to remove package from Debian.
