### ISSUE TITLE
contains D-Bus policy configuration that uses the deprecated at_console condition

### ISSUE THREAD

**Issue by ginggs** [andrewbird/wader#13]
From Debian Lintian report [dbus-policy-at-console](https://lintian.debian.org/tags/dbus-policy-at-console.html):
> The package contains D-Bus policy configuration that uses the deprecated at_console condition to impose a different policy for users who are "logged in at the console" according to systemd-logind, ConsoleKit or similar APIs, such as:
> 
>       <policy context="default">
>         <deny send_destination="com.example.PowerManagementDaemon"/>
>       </policy>
>       <policy at_console="true">
>         <allow send_destination="com.example.PowerManagementDaemon"/>
>       </policy>
>     
> 
> The maintainers of D-Bus recommend that services should allow or deny method calls according to broad categories that are not typically altered by the system administrator (usually either "all users", or only root and/or a specified system user). If finer-grained authorization is required, the service should accept the method call message, then call out to PolicyKit to decide whether to honor the request. PolicyKit can use system-administrator-configurable policies to make that decision, including distinguishing between users who are "at the console" and those who are not.
> 
> Refer to https://bugs.freedesktop.org/show_bug.cgi?id=39611 for details.

**Comment by andrewbird** [comment]
Agreed to remove package from Debian, see #12
